const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Physics,
		C3.Plugins.Keyboard,
		C3.Plugins.Particles,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Physics: 0},
	{ground: 0},
	{background: 0},
	{Border: 0},
	{ID: 0},
	{Dispenser: 0},
	{meteor: 0},
	{Keyboard: 0},
	{Particles: 0},
	{Platform: 0},
	{BoundToLayout: 0},
	{Player: 0},
	{TextScore: 0},
	{TextLives: 0},
	{Sine: 0},
	{Start: 0},
	{TextStart: 0},
	{TextLose: 0},
	{TextWIn: 0},
	{Mouse: 0},
	{randomID: 0},
	{score: 0},
	{lives: 0}
];

self.InstanceType = {
	ground: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	Border: class extends self.ISpriteInstance {},
	Dispenser: class extends self.ISpriteInstance {},
	meteor: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Particles: class extends self.IParticlesInstance {},
	Player: class extends self.ISpriteInstance {},
	TextScore: class extends self.ITextInstance {},
	TextLives: class extends self.ITextInstance {},
	Start: class extends self.ISpriteInstance {},
	TextStart: class extends self.ITextInstance {},
	TextLose: class extends self.ITextInstance {},
	TextWIn: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {}
}